@startuml Actores

left to right direction

actor Cliente
actor Tecnico

Cliente -right-> Tecnico : envia solicitud

note right of Cliente
**Cliente**:
Inicia el ciclo mediante solicitudes
y recibe respuestas del tecnico.
end note

note right of Tecnico
**Tecnico**:
Recibe solicitudes y las resuelve
end note

@enduml
