@startuml EnviarSolicitud

skinparam linetype polyline

state enviarSolicitud as "enviarSolicitud()" {

state " " as IdentificandoNecesidad
state " " as RedactandoSolicitud
state " " as RevisandoSolicitud

[*] -[#green]-> IdentificandoNecesidad
note on link
<b>Cliente</b> detecta una necesidad:
• Tiene un problema
• Quiere realizar una consulta
end note

IdentificandoNecesidad -[#green]-> RedactandoSolicitud
note on link
<b>Cliente</b> redacta la solicitud
end note

RedactandoSolicitud -[#green]-> RevisandoSolicitud
note on link
<b>Cliente</b> revisa la solicitud
end note

RevisandoSolicitud -[#green]-> [*]
note on link
<b>Cliente</b> está conforme
y envía la solicitud
end note

RevisandoSolicitud -[#red]-> RedactandoSolicitud
note on link
<b>Cliente</b> no está conforme
y modifica la solicitud
end note

}

enviarSolicitud -[#green]-> SISTEMA
note on link
Sistema
end note

enviarSolicitud -[#red]-> ERROR_ENVIO
note on link
Error al enviar la solicitud
end note

@enduml
