@startuml CdU_Tecnico
left to right direction

actor Tecnico

    usecase "Ver solicitudes pendientes" as VerSolicitudes
    usecase "Actualizar estado" as ActualizarEstado

Tecnico --> VerSolicitudes
Tecnico --> ActualizarEstado

@enduml