@startuml

[*] --> OBTENCIÓN_DE_DATOS : navegación a pestaña rendimiento

OBTENCIÓN_DE_DATOS --> CÁLCULO

CÁLCULO --> VISUALIZACIÓN_DE_DATOS

VISUALIZACIÓN_DE_DATOS --> SELECCIÓN_DE_PARTICIÓN

SELECCIÓN_DE_PARTICIÓN--> OBTENCIÓN_DE_DATOS 

VISUALIZACIÓN_DE_DATOS--> [*]

@enduml