@startuml

class Particion {
   id
   infoParticion
}

class InfoIndicador {
   idParticion
   tipoIndicador
   valor
}

class TipoIndicador {
   nombre
}

class TipoGrafica {
   nombre
}


InfoIndicador -- TipoIndicador: tipado en
Particion -- InfoIndicador: tiene
InfoIndicador -- TipoGrafica: se representa en



@enduml