@startuml

[*] --> COMUNICACION_ENTRE_BACK_Y_FRONT: navegación a pestaña rendimiento
COMUNICACION_ENTRE_BACK_Y_FRONT --> OBTENCION_DE_DATOS 

OBTENCION_DE_DATOS --> CALCULO

CALCULO --> COMUNICACION_ENTRE_BACK_Y_FRONT: pasa a front

COMUNICACION_ENTRE_BACK_Y_FRONT--> VISUALIZACION_DE_DATOS: pasa datos desde back

FILTRADO_DE_DATOS --> COMUNICACION_ENTRE_BACK_Y_FRONT: pasa a back nuevo splitId
VISUALIZACION_DE_DATOS --> FILTRADO_DE_DATOS : cambiar SplitId o fechas

VISUALIZACION_DE_DATOS --> [*]


@enduml