@startuml

start

:Responsable de producción abre pestaña Rendimiento;
:VT comprueba si hay datos de fabricación;

if (¿Hay datos teóricos y reales?) then (Sí)

else (No)
  :VT busca información en su BD;

  if (¿La encuentra en 45 s?) then (Sí)

  else (No)
    :Mostrar error;
    stop
  endif
endif

:VT realiza cálculos;
:VT grafica resultados;

stop
@enduml