@startuml

class AssignmentSplit{
   splitId
   idPuestoDeTrabajo
   splitInfoTeorica
   splitInfoEjecución
}

class VisualTracking{
   splitId
   infoTeórica
   infoEjecución
}

class SplitIndexInfo{
   splitId
   infoPiezas
   infoTiempos
   infoIndicadores
   infoCurvaVelocidad
}

class infoIndicadores{
   disponibilidad
   rendimiento
   calidad 
   OEE
}
class Graficas {
   curvaDeVelocidad
   barrasDeIndicadores
   tablaDeIndicadores
}

VisualTracking -- AssignmentSplit: obtiene info de
VisualTracking -- SplitIndexInfo: calcula
VisualTracking -- Graficas: genera

infoIndicadores-- SplitIndexInfo


@enduml