@startuml CdU_Cliente
left to right direction

actor Cliente

    
    usecase "Enviar solicitud" as EnviarCorreo
    usecase "Recibir respuesta" as RecibirRespuesta
    usecase "Completar formulario" as CompletarFormulario


Cliente --> EnviarCorreo
Cliente --> RecibirRespuesta
Cliente --> CompletarFormulario

@enduml